# Servicemonitor for  prometheus-stack
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bluerise-servicemonitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack  # must match Prometheus release label
spec:
  selector:
    matchLabels:
      app: bluerise
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - monitoring
